import { StyleSheet } from "react-native";
export const palette = {
  bg: "#070B19",
  surface: "#141A2B",
  ink: "#F5F7FF",
  muted: "#A4AEC5",
  purple: "#087EFF",
  lavender: "#142B4F",
  border: "#273149",
  mint: "#143B36",
  green: "#64E4B0",
  pink: "#412030",
  rose: "#FF657E",
  yellow: "#332D20",
  dark: "#182139",
  blue: "#087EFF",
  cyan: "#65CFFF",
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: palette.bg },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 20,
    flexGrow: 1,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  title: {
    color: palette.ink,
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: -0.3,
    lineHeight: 40,
  },
  heading: {
    color: palette.ink,
    fontSize: 21,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  body: { color: palette.muted, fontSize: 15, lineHeight: 24 },
  caption: { color: palette.muted, fontSize: 12, lineHeight: 19 },
  label: { color: palette.ink, fontSize: 14, fontWeight: "700" },
  eyebrow: {
    color: palette.purple,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
  },
  card: {
    padding: 20,
    backgroundColor: palette.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 12,
  },
  divider: { height: 1, backgroundColor: palette.border },
  grow: { flex: 1 },
});
