import { StyleSheet } from "react-native";
export const palette = {
  bg: "#FAF8FF",
  surface: "#FFFFFF",
  ink: "#242139",
  muted: "#777089",
  purple: "#634CF5",
  lavender: "#EEE9FF",
  border: "#E7E1F2",
  mint: "#DDF8ED",
  green: "#177B67",
  pink: "#FFE6EF",
  rose: "#BB365B",
  yellow: "#FFF1CF",
  dark: "#221D35",
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: palette.bg },
  content: {
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 20,
    flexGrow: 1,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  title: {
    color: palette.ink,
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: -0.9,
    lineHeight: 40,
  },
  heading: {
    color: palette.ink,
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  body: { color: palette.muted, fontSize: 15, lineHeight: 24 },
  caption: { color: palette.muted, fontSize: 12, lineHeight: 19 },
  label: { color: palette.ink, fontSize: 14, fontWeight: "700" },
  eyebrow: {
    color: palette.purple,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
  },
  card: {
    padding: 20,
    backgroundColor: palette.surface,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 12,
  },
  divider: { height: 1, backgroundColor: palette.border },
  grow: { flex: 1 },
});
